/**
 * Demo data. Both backends load this: the in-memory store on every boot, the
 * Mongo store once, when the `users` collection is empty.
 *
 * Every seeded account signs in with DEMO_PASSWORD. Times are relative to
 * "now" so nothing is ever in the past on first load.
 */

import type { Activity, Comment, UserDoc } from '$lib/types';
import { hashPassword } from './auth';

/** Bump whenever you edit the data below so a running dev server re-seeds. */
export const SEED_VERSION = 12;

export interface SeedData {
	users: UserDoc[];
	activities: Activity[];
	comments: Comment[];
}

/** Password for every seeded account shown on the login page in dev. */
export const DEMO_PASSWORD = 'tagalong';

/** Minutes/hours/days from "now", so seed data never goes stale. */
const hoursFromNow = (h: number) => new Date(Date.now() + h * 3_600_000).toISOString();
const hoursAgo = (h: number) => hoursFromNow(-h);

/**
 * Completed activities behind us, so demo gardens have something in them.
 * Spread across the demo accounts and weighted towards Mei, who is the
 * account the login page hands out.
 */
function pastRuns(): Activity[] {
	const done = (
		id: string,
		title: string,
		category: Activity['category'],
		campus: Activity['campus'],
		hostId: string,
		memberIds: string[],
		daysAgo: number,
		costCents: number,
		interests: string[]
	): Activity => ({
		id,
		title,
		body: '',
		category,
		campus,
		hostId,
		location: 'Around campus',
		startsAt: hoursFromNow(-24 * daysAgo),
		spots: memberIds.length,
		memberIds,
		waitlistIds: [],
		visibility: 'public',
		approvalRequired: false,
		// The host confirmed it the evening it happened.
		completedAt: hoursFromNow(-24 * daysAgo + 4),
		costCents,
		costBasis: 'per-person',
		createdAt: hoursFromNow(-24 * (daysAgo + 3)),
		interests
	});

	return [
		done(
			'a_past_costco1',
			'Costco run',
			'groceries',
			'cmu',
			'u_mei',
			['u_mei', 'u_nori', 'u_theo'],
			6,
			1700,
			['groceries', 'bulk buys']
		),
		done(
			'a_past_costco2',
			'Costco run',
			'groceries',
			'cmu',
			'u_mei',
			['u_mei', 'u_satsuki', 'u_lin'],
			13,
			1700,
			['groceries', 'bulk buys']
		),
		done(
			'a_past_costco3',
			'Costco run',
			'groceries',
			'cmu',
			'u_mei',
			['u_mei', 'u_nori'],
			20,
			1700,
			['groceries', 'bulk buys']
		),
		done(
			'a_past_ramen',
			'Ramen order',
			'food',
			'cmu',
			'u_theo',
			['u_theo', 'u_mei', 'u_satsuki', 'u_ava'],
			4,
			1200,
			['food']
		),
		done(
			'a_past_karaoke',
			'Karaoke night',
			'hangouts',
			'cmu',
			'u_satsuki',
			['u_satsuki', 'u_mei', 'u_pria', 'u_dev'],
			9,
			2000,
			['music']
		),
		done(
			'a_past_hike',
			'Frick Park hike',
			'hangouts',
			'cmu',
			'u_pria',
			['u_pria', 'u_satsuki', 'u_ava', 'u_marcus'],
			16,
			0,
			['outdoors']
		),
		done(
			'a_past_boardgames',
			'Board game night',
			'hangouts',
			'pitt',
			'u_kanta',
			['u_kanta', 'u_lin', 'u_dev'],
			11,
			0,
			['board games']
		),
		done(
			'a_past_airport',
			'Airport run',
			'rides',
			'pitt',
			'u_kanta',
			['u_kanta', 'u_theo', 'u_marcus'],
			18,
			1300,
			['rides', 'driving']
		),
		done(
			'a_past_ikea',
			'IKEA haul',
			'supplies',
			'pitt',
			'u_lin',
			['u_lin', 'u_kanta', 'u_nori'],
			24,
			900,
			['furniture', 'diy']
		),
		done(
			'a_past_market',
			'Farmers market',
			'groceries',
			'cmu',
			'u_ava',
			['u_ava', 'u_satsuki', 'u_pria'],
			8,
			1500,
			['farmers markets']
		),
		done(
			'a_past_ball1',
			'Pickup basketball',
			'sports',
			'cmu',
			'u_theo',
			['u_theo', 'u_mei', 'u_dev'],
			5,
			0,
			['sports', 'basketball']
		),
		done(
			'a_past_ball2',
			'Pickup basketball',
			'sports',
			'cmu',
			'u_theo',
			['u_theo', 'u_mei', 'u_marcus'],
			12,
			0,
			['sports', 'basketball']
		),
		done(
			'a_past_ball3',
			'Pickup basketball',
			'sports',
			'cmu',
			'u_theo',
			['u_theo', 'u_mei', 'u_dev'],
			19,
			0,
			['sports', 'basketball']
		)
	];
}

export function seedData(): SeedData {
	/** Every seeded account signs in with this password. */
	const demoHash = hashPassword(DEMO_PASSWORD);

	const users: UserDoc[] = [
		{
			id: 'u_mei',
			name: 'Mei Tanaka',
			handle: 'mei',
			campus: 'cmu',
			bio: 'Junior in ECE. Perpetually organizing the Costco run.',
			avatarSeed: 0,
			email: 'mei@andrew.cmu.edu',
			passwordHash: demoHash,
			interests: ['groceries', 'cooking', 'bulk buys', 'driving'],
			joinedAt: hoursAgo(24 * 240)
		},
		{
			id: 'u_satsuki',
			name: 'Satsuki Kusakabe',
			handle: 'satsuki',
			campus: 'cmu',
			bio: 'Design major. Will absolutely split your Spotify.',
			avatarSeed: 1,
			email: 'satsuki@andrew.cmu.edu',
			passwordHash: demoHash,
			interests: ['music', 'design', 'coffee', 'farmers markets'],
			joinedAt: hoursAgo(24 * 190)
		},
		{
			id: 'u_kanta',
			name: 'Kanta Ogaki',
			handle: 'kanta',
			campus: 'pitt',
			bio: 'Bio pre-med, lives in Oakland, has a car.',
			avatarSeed: 2,
			email: 'kanta@pitt.edu',
			passwordHash: demoHash,
			interests: ['driving', 'travel', 'early mornings', 'pre-med'],
			joinedAt: hoursAgo(24 * 150)
		},
		{
			id: 'u_nori',
			name: 'Nori Alvarez',
			handle: 'nori',
			campus: 'cmu',
			bio: 'CS + stats. Optimizing my grocery budget like a DP problem.',
			avatarSeed: 3,
			email: 'nori@andrew.cmu.edu',
			passwordHash: demoHash,
			interests: ['groceries', 'budgeting', 'cooking', 'textbooks'],
			joinedAt: hoursAgo(24 * 95)
		},
		{
			id: 'u_pria',
			name: 'Pria Raghunathan',
			handle: 'pria',
			campus: 'chatham',
			bio: 'Env science. Carpool evangelist.',
			avatarSeed: 4,
			email: 'pria@chatham.edu',
			passwordHash: demoHash,
			interests: ['carpools', 'sustainability', 'errands', 'hiking'],
			joinedAt: hoursAgo(24 * 70)
		},
		{
			id: 'u_dev',
			name: 'Dev Okonkwo',
			handle: 'dev',
			campus: 'duquesne',
			bio: 'Business. Always three people short of a delivery minimum.',
			avatarSeed: 5,
			email: 'dev@duq.edu',
			passwordHash: demoHash,
			interests: ['subscriptions', 'food delivery', 'board games'],
			joinedAt: hoursAgo(24 * 40)
		},
		{
			id: 'u_lin',
			name: 'Lin Zhou',
			handle: 'lin',
			campus: 'pitt',
			bio: 'Materials sci. IKEA trip enthusiast.',
			avatarSeed: 6,
			email: 'lin@pitt.edu',
			passwordHash: demoHash,
			interests: ['furniture', 'ikea', 'diy', 'farmers markets'],
			joinedAt: hoursAgo(24 * 30)
		},
		{
			id: 'u_theo',
			name: 'Theo Marsh',
			handle: 'theo',
			campus: 'cmu',
			bio: 'Drama. Needs a ride to the airport roughly always.',
			avatarSeed: 7,
			email: 'theo@andrew.cmu.edu',
			passwordHash: demoHash,
			interests: ['food', 'theatre', 'airport runs', 'late nights'],
			joinedAt: hoursAgo(24 * 12)
		},
		{
			id: 'u_ava',
			name: 'Ava Lindqvist',
			handle: 'ava',
			campus: 'psu',
			bio: 'Penn State. Drives to Pittsburgh most weekends.',
			avatarSeed: 0,
			email: 'ava@psu.edu',
			passwordHash: demoHash,
			interests: ['road trips', 'driving', 'music'],
			joinedAt: hoursAgo(24 * 20)
		},
		{
			id: 'u_marcus',
			name: 'Marcus Bell',
			handle: 'marcus',
			campus: 'wvu',
			bio: 'WVU. Bulk-buys everything.',
			avatarSeed: 5,
			email: 'marcus@mix.wvu.edu',
			passwordHash: demoHash,
			interests: ['groceries', 'bulk buys', 'trucks'],
			joinedAt: hoursAgo(24 * 9)
		}
	];

	/* Not a student: signed up with a personal address. Sees public activities
	   only, which is the whole point of the tier. */
	users.push({
		id: 'u_sam',
		name: 'Sam Reyes',
		handle: 'sam',
		campus: 'cmu',
		accountType: 'general',
		bio: 'Not a student, just live in Shadyside and like a good Costco run.',
		avatarSeed: 5,
		email: 'sam.reyes@gmail.com',
		passwordHash: demoHash,
		interests: ['groceries', 'food', 'outdoors'],
		joinedAt: hoursAgo(24 * 30)
	});

	const activities: Activity[] = [
		{
			id: 'a_spotify',
			visibility: 'students',
			title: 'Spotify Duo, 1 slot left, $6/mo',
			body: "Family plan, 4 of us on it already. Need one more to bring everyone's share down. Venmo monthly, I'll add you the same day. Must be able to set your address to Pittsburgh.",
			category: 'subscriptions',
			campus: 'cmu',
			hostId: 'u_satsuki',
			location: 'Online, Venmo @satsuki',
			startsAt: hoursFromNow(48),
			spots: 6,
			memberIds: ['u_satsuki', 'u_nori', 'u_mei', 'u_theo', 'u_lin'],
			costCents: 600,
			costBasis: 'per-person',
			interests: ['music', 'subscriptions'],
			createdAt: hoursAgo(5)
		},
		{
			id: 'a_costco',
			title: 'Costco run Saturday: I drive, we split gas + membership',
			body: 'Heading out ~10am Saturday, back by 1. Room for 3. Split is gas ($12ish) plus $5 each toward my membership. Bring your own bags, we are not paying for boxes again.',
			category: 'groceries',
			campus: 'cmu',
			hostId: 'u_mei',
			location: "Morewood Ave lot (meet by Tepper's doors)",
			startsAt: hoursFromNow(31),
			spots: 4,
			memberIds: ['u_mei', 'u_nori'],
			costCents: 1700,
			costBasis: 'per-person',
			interests: ['groceries', 'bulk buys', 'driving'],
			createdAt: hoursAgo(9)
		},
		{
			id: 'a_airport',
			approvalRequired: true,
			title: 'PIT airport Uber, Friday 6am, splitting 4 ways',
			body: "Flight is at 8:40 so I'm leaving at 6 sharp. UberXL from Oakland is about $52, which is $13 each if we fill it. I'll book and you Venmo me at the curb.",
			category: 'rides',
			campus: 'pitt',
			hostId: 'u_kanta',
			location: 'Forbes & Bouquet',
			startsAt: hoursFromNow(80),
			spots: 4,
			memberIds: ['u_kanta', 'u_theo', 'u_pria'],
			costCents: 5200,
			costBasis: 'total',
			interests: ['travel', 'airport runs', 'early mornings'],
			createdAt: hoursAgo(14)
		},
		{
			id: 'a_ikea',
			visibility: 'private',
			approvalRequired: true,
			title: 'IKEA Robinson haul, need 2 more for the car',
			body: "Getting a desk and a shelf, there's room for two people and their flat-packs. Leaving Sunday noon. Gas split only, no charge for the trunk space.",
			category: 'supplies',
			campus: 'pitt',
			hostId: 'u_lin',
			location: 'Sutherland Hall circle',
			startsAt: hoursFromNow(60),
			spots: 3,
			memberIds: ['u_lin'],
			costCents: 900,
			costBasis: 'per-person',
			interests: ['furniture', 'ikea', 'diy'],
			createdAt: hoursAgo(20)
		},
		{
			id: 'a_ramen',
			visibility: 'campus',
			title: 'Hitting the $35 delivery minimum at Ramen Bar',
			body: 'Ordering in ~40 min. I need about $12 more on the ticket to clear the minimum and kill the small-order fee. Drop what you want in the comments, meet in the Donner lounge.',
			category: 'food',
			campus: 'cmu',
			hostId: 'u_theo',
			location: 'Donner House lounge',
			startsAt: hoursFromNow(1),
			spots: 5,
			memberIds: ['u_theo', 'u_satsuki'],
			costCents: 3500,
			costBasis: 'total',
			interests: ['food', 'food delivery'],
			createdAt: hoursAgo(1)
		},
		{
			id: 'a_giant_eagle',
			title: 'Weekly Giant Eagle walk, produce split',
			body: 'Every Tuesday. We buy the big bags of produce and divide them up on the walk back. Way cheaper than buying singles and nothing rots before you eat it.',
			category: 'groceries',
			campus: 'cmu',
			hostId: 'u_nori',
			location: 'Giant Eagle, Shadyside',
			startsAt: hoursFromNow(26),
			spots: 6,
			memberIds: ['u_nori', 'u_mei', 'u_satsuki', 'u_theo'],
			costCents: 0,
			costBasis: 'per-person',
			interests: ['groceries', 'cooking', 'walking'],
			createdAt: hoursAgo(30)
		},
		{
			id: 'a_nyt',
			title: 'NYT + Games group sub, $2.50 each',
			body: 'Have 3 of 5 seats filled on the group subscription. Includes Cooking and Games. Annual, so it is one Venmo and then you forget about it.',
			category: 'subscriptions',
			campus: 'duquesne',
			hostId: 'u_dev',
			location: 'Online',
			startsAt: hoursFromNow(120),
			spots: 5,
			memberIds: ['u_dev', 'u_kanta', 'u_pria'],
			costCents: 250,
			costBasis: 'per-person',
			interests: ['subscriptions', 'reading', 'board games'],
			createdAt: hoursAgo(36)
		},
		{
			id: 'a_laundry',
			title: 'Laundromat carpool + detergent bulk split',
			body: 'The machines in my building eat quarters. Driving to the laundromat on Murray, and a Costco-size detergent split four ways is roughly nothing per load.',
			category: 'errands',
			campus: 'chatham',
			hostId: 'u_pria',
			location: 'Murray Ave laundromat',
			startsAt: hoursFromNow(52),
			spots: 4,
			memberIds: ['u_pria', 'u_dev'],
			costCents: 800,
			costBasis: 'per-person',
			interests: ['errands', 'carpools'],
			createdAt: hoursAgo(44)
		},
		{
			id: 'a_textbook',
			title: 'Splitting the 21-241 textbook rental',
			body: 'Rental is $60 for the semester. Two of us can share. I need it Mon/Wed, you take it Tue/Thu/weekend. Has worked fine for me twice now.',
			category: 'supplies',
			campus: 'cmu',
			hostId: 'u_nori',
			location: 'Hunt Library, 2nd floor',
			startsAt: hoursFromNow(18),
			spots: 2,
			memberIds: ['u_nori', 'u_mei'],
			costCents: 6000,
			costBasis: 'total',
			interests: ['textbooks', 'budgeting', 'studying'],
			createdAt: hoursAgo(52)
		},
		{
			id: 'a_farmers',
			title: 'Squirrel Hill farmers market, bulk eggs & bread',
			body: 'The stands do way better prices by the dozen/loaf if you buy a lot. Four of us clears the bulk tier easily. Sunday morning, walkable from campus.',
			category: 'groceries',
			campus: 'cmu',
			hostId: 'u_satsuki',
			location: 'Beacon St lot, Squirrel Hill',
			startsAt: hoursFromNow(70),
			spots: 5,
			memberIds: ['u_satsuki', 'u_lin', 'u_nori'],
			costCents: 1200,
			costBasis: 'per-person',
			interests: ['farmers markets', 'cooking', 'groceries'],
			createdAt: hoursAgo(66)
		},
		{
			id: 'a_free_pizza',
			title: 'Free pizza, leftovers from the SCS town hall',
			body: 'Six untouched boxes in the Gates 6th floor kitchen. First come first served. Bring a container if you want to take slices back.',
			category: 'food',
			campus: 'cmu',
			hostId: 'u_theo',
			location: 'Gates 6th floor kitchen',
			startsAt: hoursFromNow(2),
			spots: 12,
			memberIds: ['u_theo', 'u_satsuki', 'u_nori'],
			costCents: 0,
			costBasis: 'per-person',
			interests: ['food', 'free stuff'],
			createdAt: hoursAgo(0.5)
		},
		{
			id: 'a_free_couch',
			title: 'Free couch + two lamps, moving out Sunday',
			body: "Grey IKEA loveseat, no stains, and two floor lamps. You haul, you keep. I'm on the 2nd floor with no elevator, so bring a friend.",
			category: 'supplies',
			campus: 'pitt',
			hostId: 'u_lin',
			location: 'Atwood St, Oakland',
			startsAt: hoursFromNow(58),
			spots: 2,
			memberIds: ['u_lin'],
			costCents: 0,
			costBasis: 'per-person',
			interests: ['furniture', 'free stuff', 'moving'],
			createdAt: hoursAgo(3)
		},
		{
			id: 'a_psu_ride',
			title: 'State College → Pittsburgh, Friday 4pm, 2 seats',
			body: 'Driving down for the weekend, coming back Sunday night. Split gas both ways, about $15 each way. Pickup by the HUB.',
			category: 'rides',
			campus: 'psu',
			hostId: 'u_ava',
			location: 'HUB-Robeson Center, University Park',
			startsAt: hoursFromNow(90),
			spots: 3,
			memberIds: ['u_ava'],
			costCents: 3000,
			costBasis: 'per-person',
			interests: ['road trips', 'driving', 'travel'],
			createdAt: hoursAgo(6)
		},
		{
			id: 'a_wvu_sams',
			title: "Sam's Club run Sunday, Morgantown",
			body: 'I have the membership and a truck. Three seats, split gas, bring your list. Back by 3.',
			category: 'groceries',
			campus: 'wvu',
			hostId: 'u_marcus',
			location: 'Mountainlair front steps',
			startsAt: hoursFromNow(55),
			spots: 4,
			memberIds: ['u_marcus'],
			costCents: 600,
			costBasis: 'per-person',
			interests: ['groceries', 'bulk buys', 'driving'],
			createdAt: hoursAgo(12)
		},
		{
			id: 'a_karaoke',
			title: 'Karaoke in Shadyside Friday, room fits 6',
			body: "Booked a room 9pm–11pm, it's $60 split however many show up. No talent required, we are all terrible.",
			category: 'hangouts',
			campus: 'cmu',
			hostId: 'u_satsuki',
			location: 'Tiki Lounge, Shadyside',
			startsAt: hoursFromNow(44),
			spots: 6,
			memberIds: ['u_satsuki', 'u_theo'],
			costCents: 6000,
			costBasis: 'total',
			interests: ['music', 'board games'],
			createdAt: hoursAgo(4)
		},
		{
			id: 'a_frick_hike',
			title: 'Easy Frick Park loop Sunday morning',
			body: 'About 4 miles, casual pace, back by noon. Free, just show up. Dogs welcome.',
			category: 'hangouts',
			campus: 'pitt',
			hostId: 'u_kanta',
			location: 'Frick Park, Beechwood entrance',
			startsAt: hoursFromNow(64),
			spots: 8,
			memberIds: ['u_kanta', 'u_pria'],
			costCents: 0,
			costBasis: 'per-person',
			interests: ['outdoors', 'fitness'],
			createdAt: hoursAgo(16)
		},
		{
			id: 'a_study_hunt',
			title: 'Finals grind at Hunt, 3rd floor, all day Saturday',
			body: 'Claiming the big table at 10am. Come and go as you like, we take a coffee run every couple of hours.',
			category: 'hangouts',
			campus: 'cmu',
			hostId: 'u_nori',
			location: 'Hunt Library, 3rd floor',
			startsAt: hoursFromNow(34),
			spots: 10,
			memberIds: ['u_nori', 'u_mei'],
			costCents: 0,
			costBasis: 'per-person',
			interests: ['studying', 'coffee'],
			createdAt: hoursAgo(8)
		},
		{
			id: 'a_nyc_weekend',
			title: 'NYC weekend trip: museums + food',
			body: 'Going to NYC for the weekend and looking for a few people to explore museums, try restaurants, and split transportation.',
			category: 'hangouts',
			campus: 'cmu',
			hostId: 'u_mei',
			location: 'New York, NY',
			startsAt: hoursFromNow(72),
			spots: 4,
			memberIds: ['u_mei'],
			costCents: 18000,
			costBasis: 'per-person',
			createdAt: hoursAgo(2),
			interests: ['travel', 'museums', 'food', 'art', 'city exploring']
		},
		{
			id: 'a_pit_airport',
			title: 'Split an Uber to PIT airport',
			body: 'Leaving campus early Friday morning. Looking for up to 3 people with similar flight times to split an Uber.',
			category: 'rides',
			campus: 'cmu',
			hostId: 'u_theo',
			location: 'Pittsburgh International Airport',
			startsAt: hoursFromNow(42),
			spots: 4,
			memberIds: ['u_theo'],
			costCents: 5600,
			costBasis: 'total',
			createdAt: hoursAgo(4),
			interests: ['travel', 'airports', 'budget travel']
		},
		{
			id: 'a_hiking',
			title: 'Ohiopyle hiking day trip',
			body: 'Planning a Saturday hiking trip. Beginner-friendly trails, lunch outside, and splitting gas.',
			category: 'hangouts',
			campus: 'pitt',
			hostId: 'u_kanta',
			location: 'Ohiopyle State Park',
			startsAt: hoursFromNow(96),
			spots: 5,
			memberIds: ['u_kanta'],
			costCents: 1500,
			costBasis: 'per-person',
			createdAt: hoursAgo(8),
			interests: ['hiking', 'nature', 'outdoors', 'photography', 'fitness']
		},
		{
			id: 'a_thrift',
			title: 'Thrifting in Lawrenceville',
			body: 'Going around a few thrift and vintage stores Saturday afternoon. Looking for people who like fashion and secondhand finds.',
			category: 'hangouts',
			campus: 'cmu',
			hostId: 'u_satsuki',
			location: 'Lawrenceville, Pittsburgh',
			startsAt: hoursFromNow(28),
			spots: 4,
			memberIds: ['u_satsuki'],
			costCents: 0,
			costBasis: 'per-person',
			createdAt: hoursAgo(3),
			interests: ['fashion', 'thrifting', 'shopping', 'sustainability']
		},
		{
			id: 'a_concert',
			title: 'Concert downtown, split ride',
			body: 'Going to a concert downtown and would love a group to go together and split the ride back.',
			category: 'rides',
			campus: 'duquesne',
			hostId: 'u_dev',
			location: 'Downtown Pittsburgh',
			startsAt: hoursFromNow(54),
			spots: 4,
			memberIds: ['u_dev'],
			costCents: 3200,
			costBasis: 'total',
			createdAt: hoursAgo(6),
			interests: ['music', 'concerts', 'nightlife', 'pop']
		},
		{
			id: 'a_coffee',
			title: 'Coffee shop study crawl',
			body: 'Trying a couple coffee shops around Shadyside while getting work done. Chill group, bring homework.',
			category: 'food',
			campus: 'cmu',
			hostId: 'u_nori',
			location: 'Shadyside, Pittsburgh',
			startsAt: hoursFromNow(20),
			spots: 5,
			memberIds: ['u_nori'],
			costCents: 1200,
			costBasis: 'per-person',
			createdAt: hoursAgo(1),
			interests: ['coffee', 'studying', 'academics', 'cafes', 'productivity']
		},
		{
			id: 'a_rock_climbing',
			title: 'Beginner rock climbing',
			body: 'Going climbing this weekend. Totally fine if you have never climbed before. Looking for a few people to go together.',
			category: 'sports',
			campus: 'pitt',
			hostId: 'u_pria',
			location: 'Ascend Pittsburgh',
			startsAt: hoursFromNow(46),
			spots: 6,
			memberIds: ['u_pria'],
			costCents: 2800,
			costBasis: 'per-person',
			createdAt: hoursAgo(9),
			interests: ['climbing', 'fitness', 'sports', 'adventure']
		},
		{
			id: 'a_board_games',
			title: 'Board game night',
			body: 'Casual board game night. We have Codenames, Ticket to Ride, Coup, and a bunch more.',
			category: 'hangouts',
			campus: 'cmu',
			hostId: 'u_lin',
			location: 'Morewood Gardens',
			startsAt: hoursFromNow(12),
			spots: 8,
			memberIds: ['u_lin', 'u_mei'],
			costCents: 0,
			costBasis: 'per-person',
			createdAt: hoursAgo(2),
			interests: ['board games', 'games', 'social', 'strategy']
		},
		{
			id: 'a_korean_food',
			title: 'Korean food group dinner',
			body: 'Want to try a Korean restaurant but portions are huge. Looking for a group so we can order several dishes and share.',
			category: 'food',
			campus: 'cmu',
			hostId: 'u_satsuki',
			location: 'Oakland, Pittsburgh',
			startsAt: hoursFromNow(24),
			spots: 5,
			memberIds: ['u_satsuki'],
			costCents: 2500,
			costBasis: 'per-person',
			createdAt: hoursAgo(5),
			interests: ['food', 'korean food', 'restaurants', 'culture']
		},
		{
			id: 'a_art_museum',
			title: 'Carnegie Museum of Art afternoon',
			body: 'Going through the art museum slowly and taking photos/sketching. Looking for other artsy people.',
			category: 'hangouts',
			campus: 'cmu',
			hostId: 'u_mei',
			location: 'Carnegie Museum of Art',
			startsAt: hoursFromNow(30),
			spots: 4,
			memberIds: ['u_mei'],
			costCents: 1500,
			costBasis: 'per-person',
			createdAt: hoursAgo(7),
			interests: ['art', 'museums', 'drawing', 'photography', 'design']
		},
		{
			id: 'a_anime',
			title: 'Anime movie night',
			body: 'Watching a couple movies and ordering snacks. Open to suggestions.',
			category: 'hangouts',
			campus: 'cmu',
			hostId: 'u_theo',
			location: 'Donner lounge',
			startsAt: hoursFromNow(15),
			spots: 10,
			memberIds: ['u_theo'],
			costCents: 500,
			costBasis: 'per-person',
			createdAt: hoursAgo(3),
			interests: ['anime', 'movies', 'japanese culture', 'social']
		},
		{
			id: 'a_photowalk',
			title: 'Sunset photography walk',
			body: 'Walking around Schenley and taking sunset photos. Phone cameras completely welcome.',
			category: 'hangouts',
			campus: 'pitt',
			hostId: 'u_kanta',
			location: 'Schenley Park',
			startsAt: hoursFromNow(18),
			spots: 6,
			memberIds: ['u_kanta'],
			costCents: 0,
			costBasis: 'per-person',
			createdAt: hoursAgo(2),
			interests: ['photography', 'nature', 'walking', 'art']
		},
		{
			id: 'a_baking',
			title: 'Bake cookies + split ingredients',
			body: 'Want to bake way too many cookies without buying every ingredient individually. Looking for 3–4 people.',
			category: 'food',
			campus: 'chatham',
			hostId: 'u_pria',
			location: 'Chatham student kitchen',
			startsAt: hoursFromNow(36),
			spots: 5,
			memberIds: ['u_pria'],
			costCents: 800,
			costBasis: 'per-person',
			createdAt: hoursAgo(4),
			interests: ['baking', 'food', 'cooking', 'desserts']
		},
		{
			id: 'a_coding',
			title: 'Weekend coding / side project session',
			body: 'Working on personal projects for a few hours. Looking for other CS people who want accountability and company.',
			category: 'hangouts',
			campus: 'cmu',
			hostId: 'u_nori',
			location: 'Gates Center',
			startsAt: hoursFromNow(34),
			spots: 6,
			memberIds: ['u_nori'],
			costCents: 0,
			costBasis: 'per-person',
			createdAt: hoursAgo(1),
			interests: ['coding', 'computer science', 'AI', 'startups', 'productivity']
		},
		{
			id: 'a_robotics',
			title: 'Robotics expo group',
			body: 'Planning to check out the robotics demos and would love to go with people interested in hardware or AI.',
			category: 'hangouts',
			campus: 'cmu',
			hostId: 'u_mei',
			location: 'Newell-Simon Hall',
			startsAt: hoursFromNow(40),
			spots: 6,
			memberIds: ['u_mei'],
			costCents: 0,
			costBasis: 'per-person',
			createdAt: hoursAgo(6),
			interests: ['robotics', 'AI', 'engineering', 'technology']
		},
		{
			id: 'a_yoga',
			title: 'Morning yoga in Schenley',
			body: 'Low-key outdoor yoga session. Beginners welcome.',
			category: 'sports',
			campus: 'pitt',
			hostId: 'u_lin',
			location: 'Schenley Plaza',
			startsAt: hoursFromNow(22),
			spots: 8,
			memberIds: ['u_lin'],
			costCents: 0,
			costBasis: 'per-person',
			createdAt: hoursAgo(3),
			interests: ['yoga', 'wellness', 'fitness', 'outdoors']
		},
		{
			id: 'a_running',
			title: 'Easy 5K morning run',
			body: 'Conversational pace, not a race. Looking for people who want a casual running group.',
			category: 'sports',
			campus: 'cmu',
			hostId: 'u_theo',
			location: 'Schenley Park',
			startsAt: hoursFromNow(25),
			spots: 8,
			memberIds: ['u_theo'],
			costCents: 0,
			costBasis: 'per-person',
			createdAt: hoursAgo(5),
			interests: ['running', 'fitness', 'outdoors', 'health']
		},
		{
			id: 'a_bookstore',
			title: 'Used bookstore afternoon',
			body: 'Checking out used bookstores and grabbing coffee afterward.',
			category: 'hangouts',
			campus: 'chatham',
			hostId: 'u_pria',
			location: 'Squirrel Hill',
			startsAt: hoursFromNow(44),
			spots: 4,
			memberIds: ['u_pria'],
			costCents: 0,
			costBasis: 'per-person',
			createdAt: hoursAgo(10),
			interests: ['books', 'reading', 'coffee', 'literature']
		},
		{
			id: 'a_language_exchange',
			title: 'Mandarin / English language exchange',
			body: 'Casual conversation practice. Half the time Mandarin, half English.',
			category: 'hangouts',
			campus: 'cmu',
			hostId: 'u_mei',
			location: 'Hunt Library',
			startsAt: hoursFromNow(27),
			spots: 6,
			memberIds: ['u_mei'],
			costCents: 0,
			costBasis: 'per-person',
			createdAt: hoursAgo(4),
			interests: ['languages', 'mandarin', 'culture', 'learning']
		},
		{
			id: 'a_volunteer',
			title: 'Volunteer at local food bank',
			body: 'Going to a weekend volunteer shift. Looking for others who want to come together and split transportation.',
			category: 'hangouts',
			campus: 'duquesne',
			hostId: 'u_dev',
			location: 'Greater Pittsburgh Community Food Bank',
			startsAt: hoursFromNow(75),
			spots: 5,
			memberIds: ['u_dev'],
			costCents: 1000,
			costBasis: 'total',
			createdAt: hoursAgo(12),
			interests: ['volunteering', 'community service', 'social impact']
		},
		{
			id: 'a_escape_room',
			title: 'Escape room, need 3 more people',
			body: 'Group rate gets much cheaper with six people. Looking for people who like puzzles.',
			category: 'hangouts',
			campus: 'cmu',
			hostId: 'u_nori',
			location: 'Downtown Pittsburgh',
			startsAt: hoursFromNow(50),
			spots: 6,
			memberIds: ['u_nori', 'u_satsuki', 'u_theo'],
			costCents: 18000,
			costBasis: 'total',
			createdAt: hoursAgo(6),
			interests: ['puzzles', 'games', 'escape rooms', 'strategy']
		},
		{
			id: 'a_boba',
			title: 'Boba + walk around Oakland',
			body: 'Getting boba and walking around for a bit. Super casual.',
			category: 'food',
			campus: 'pitt',
			hostId: 'u_kanta',
			location: 'Oakland',
			startsAt: hoursFromNow(10),
			spots: 5,
			memberIds: ['u_kanta'],
			costCents: 700,
			costBasis: 'per-person',
			createdAt: hoursAgo(1),
			interests: ['boba', 'food', 'walking', 'social']
		},
		{
			id: 'a_pottery',
			title: 'Pottery painting afternoon',
			body: 'Going pottery painting this weekend and looking for other creative people.',
			category: 'hangouts',
			campus: 'chatham',
			hostId: 'u_pria',
			location: 'Shadyside',
			startsAt: hoursFromNow(62),
			spots: 4,
			memberIds: ['u_pria'],
			costCents: 2600,
			costBasis: 'per-person',
			createdAt: hoursAgo(8),
			interests: ['art', 'pottery', 'crafts', 'design']
		},
		{
			id: 'a_video_games',
			title: 'Mario Kart tournament',
			body: 'Casual tournament, no actual skill required. Snacks included.',
			category: 'hangouts',
			campus: 'cmu',
			hostId: 'u_theo',
			location: 'Morewood lounge',
			startsAt: hoursFromNow(16),
			spots: 10,
			memberIds: ['u_theo', 'u_nori'],
			costCents: 0,
			costBasis: 'per-person',
			createdAt: hoursAgo(2),
			interests: ['video games', 'nintendo', 'gaming', 'social']
		},
		{
			id: 'a_ski',
			title: 'Seven Springs ski trip',
			body: 'Planning a full-day ski trip. Looking for people to split gas and possibly rentals.',
			category: 'hangouts',
			campus: 'cmu',
			hostId: 'u_lin',
			location: 'Seven Springs',
			startsAt: hoursFromNow(140),
			spots: 5,
			memberIds: ['u_lin'],
			costCents: 8500,
			costBasis: 'per-person',
			createdAt: hoursAgo(15),
			interests: ['skiing', 'snowboarding', 'outdoors', 'adventure', 'travel']
		},
		{
			id: 'a_farmers_market',
			title: 'Farmers market + brunch',
			body: 'Going to the farmers market in the morning and grabbing brunch afterward.',
			category: 'food',
			campus: 'cmu',
			hostId: 'u_satsuki',
			location: 'Squirrel Hill',
			startsAt: hoursFromNow(68),
			spots: 5,
			memberIds: ['u_satsuki'],
			costCents: 2000,
			costBasis: 'per-person',
			createdAt: hoursAgo(10),
			interests: ['food', 'farmers markets', 'brunch', 'local businesses']
		},
		{
			id: 'a_movie',
			title: 'Horror movie theater group',
			body: 'Seeing the new horror movie Friday night. Looking for people who will not judge me for screaming.',
			category: 'hangouts',
			campus: 'pitt',
			hostId: 'u_kanta',
			location: 'SouthSide Works Cinema',
			startsAt: hoursFromNow(35),
			spots: 6,
			memberIds: ['u_kanta'],
			costCents: 1600,
			costBasis: 'per-person',
			createdAt: hoursAgo(4),
			interests: ['movies', 'horror', 'cinema', 'social']
		},
		{
			id: 'a_picnic',
			title: 'Schenley picnic + frisbee',
			body: 'Bringing snacks and a frisbee. Come hang out for an hour or stay all afternoon.',
			category: 'food',
			campus: 'cmu',
			hostId: 'u_mei',
			location: 'Schenley Park',
			startsAt: hoursFromNow(21),
			spots: 10,
			memberIds: ['u_mei', 'u_theo'],
			costCents: 500,
			costBasis: 'per-person',
			createdAt: hoursAgo(2),
			interests: ['frisbee', 'sports', 'picnic', 'outdoors', 'social']
		},
		{
			id: 'a_makeup',
			title: 'Makeup + getting ready before formal',
			body: 'Getting ready together before formal. Bring whatever products you like and we can share mirrors/tools.',
			category: 'hangouts',
			campus: 'cmu',
			hostId: 'u_satsuki',
			location: 'Morewood Gardens',
			startsAt: hoursFromNow(32),
			spots: 6,
			memberIds: ['u_satsuki'],
			costCents: 0,
			costBasis: 'per-person',
			createdAt: hoursAgo(4),
			interests: ['makeup', 'fashion', 'beauty', 'social']
		},
		{
			id: 'a_startup',
			title: 'Startup idea brainstorming',
			body: 'Casual meetup for people interested in startups, product ideas, and building things.',
			category: 'hangouts',
			campus: 'cmu',
			hostId: 'u_nori',
			location: 'Tepper Quad',
			startsAt: hoursFromNow(29),
			spots: 7,
			memberIds: ['u_nori'],
			costCents: 0,
			costBasis: 'per-person',
			createdAt: hoursAgo(5),
			interests: ['startups', 'entrepreneurship', 'technology', 'business', 'coding']
		},
		{
			id: 'a_dance',
			title: 'Beginner dance workshop',
			body: 'Going to a beginner dance workshop. No experience expected.',
			category: 'hangouts',
			campus: 'pitt',
			hostId: 'u_kanta',
			location: 'Oakland',
			startsAt: hoursFromNow(38),
			spots: 8,
			memberIds: ['u_kanta'],
			costCents: 1000,
			costBasis: 'per-person',
			createdAt: hoursAgo(7),
			interests: ['dance', 'music', 'fitness', 'performing arts']
		},
		{
			id: 'a_mental_health',
			title: 'Wellness walk + tea',
			body: 'Low-pressure walk around campus followed by tea. Just a chill break from studying.',
			category: 'hangouts',
			campus: 'cmu',
			hostId: 'u_pria',
			location: 'CMU campus',
			startsAt: hoursFromNow(14),
			spots: 6,
			memberIds: ['u_pria'],
			costCents: 500,
			costBasis: 'per-person',
			createdAt: hoursAgo(2),
			interests: ['wellness', 'mental health', 'walking', 'tea', 'relaxation']
		},

		{
			id: 'a_basketball',
			title: 'Pickup basketball, Tuesday nights',
			body: 'Regular run at the Cohon gym courts. Usually 8 to 10 of us, all skill levels. Free with your student ID, just bring a light and a dark shirt.',
			category: 'sports',
			campus: 'cmu',
			hostId: 'u_theo',
			location: 'Cohon Center courts',
			startsAt: hoursFromNow(29),
			spots: 10,
			memberIds: ['u_theo', 'u_dev', 'u_marcus'],
			costCents: 0,
			costBasis: 'per-person',
			createdAt: hoursAgo(11),
			interests: ['sports', 'basketball', 'fitness']
		},
		{
			id: 'a_tennis',
			title: 'Tennis court time, splitting the hourly rate',
			body: 'Booked two hours on Sunday morning. The court is $24 an hour and I need three more people to make it worth it. Rackets available if you do not have one.',
			category: 'sports',
			campus: 'pitt',
			hostId: 'u_ava',
			location: 'Mellon Park courts',
			startsAt: hoursFromNow(58),
			spots: 4,
			memberIds: ['u_ava'],
			costCents: 4800,
			costBasis: 'total',
			createdAt: hoursAgo(6),
			interests: ['sports', 'tennis', 'fitness']
		},
		{
			id: 'a_soccer',
			title: 'Sunday league soccer, need subs',
			body: 'Casual rec league over at the Oakland fields. We are short two people most weeks. No league fee, just show up in cleats.',
			category: 'sports',
			campus: 'pitt',
			hostId: 'u_kanta',
			location: 'Oakland rec fields',
			startsAt: hoursFromNow(70),
			spots: 8,
			memberIds: ['u_kanta', 'u_lin'],
			costCents: 0,
			costBasis: 'per-person',
			createdAt: hoursAgo(15),
			interests: ['sports', 'soccer', 'outdoors']
		},

		/* ---- history ------------------------------------------------------
		   Activities that already happened and that their hosts confirmed.
		   These are the only ones that count as grass, so without a few the
		   demo profiles would all be bare patches. */
		...pastRuns()
	];

	const comments: Comment[] = [
		{
			id: 'c_1',
			activityId: 'a_costco',
			authorId: 'u_theo',
			body: 'Is there room for a case of seltzer or are we tight on trunk space?',
			createdAt: hoursAgo(7)
		},
		{
			id: 'c_2',
			activityId: 'a_costco',
			authorId: 'u_mei',
			body: 'Trunk is fine, back seat is the tight part. Seltzer is welcome.',
			createdAt: hoursAgo(6)
		},
		{
			id: 'c_3',
			activityId: 'a_spotify',
			authorId: 'u_nori',
			body: 'Can confirm, been on this plan since March and it has never broken.',
			createdAt: hoursAgo(4)
		},
		{
			id: 'c_4',
			activityId: 'a_airport',
			authorId: 'u_pria',
			body: 'In. I only have a carry-on so the trunk is all yours.',
			createdAt: hoursAgo(11)
		},
		{
			id: 'c_5',
			activityId: 'a_ramen',
			authorId: 'u_satsuki',
			body: 'Spicy miso + gyoza for me, sending $14 now.',
			createdAt: hoursAgo(1)
		}
	];

	return { users, activities, comments };
}
